apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "app", "namespace": "", "kind": "DeploymentConfig"}]'
  name: app-example-pipeline
  namespace: ci-cd
spec:
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'http://gogs-ci-cd.apps.example.com/gogsadmin/app-example.git'
    sourceSecret:
      name: jenkins-ephemeral-parameters24oc4
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers: []
